### ISSUE TITLE
Windows setup

### ISSUE THREAD

**Issue by horseyhorsey** [freezy/node-vpdb#34]
Just some things I ran into during the setup.

[Node JS]
(https://nodejs.org/en/)

[Redis](https://github.com/MSOpenTech/redis/releases)

Server install command.
`<redis-server --service-install redis.windows.conf --loglevel verbose -- service-name redisService>`

**Comment by horseyhorsey** [comment]
<'npm install -g bower'>

**Comment by freezy** [comment]
You this is missing from the README? Or what's the point of this issue?

**Comment by horseyhorsey** [comment]
readme
